name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        build_dir: .
      env:
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
